[package]
name = "money-pot"
version = "1.0.0"
authors = ["Hiro <laciferin@gmail.com>"]
upgrade_policy = "compatible"

[addresses]
money_pot = "_"  # Assigned at publish time
trusted_oracle = "0xb2530c42d161bab8d925e8227ee832bc79ac2edde9218f3b10f4d2385594a230"
platform = "0x76eccd8c44038ccd0cadebd72e362c5f4c3f530145b70c8fb5b16539566b178b"
usdc = "0x69091fbab5f7d635ee7ac5098cf0c1efbe31d68fec0f2cd565e8d168daf52832"


[dev-addresses]
money_pot = "0x111111"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework/", rev = "mainnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-stdlib/", rev = "mainnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token/", rev = "mainnet" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "move-stdlib/", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-token-objects/", rev = "mainnet" }
